[skip ci] New CircleCI config
Ref: https://github.com/greenpeace/planet4-nro-generator/blob/72d660c3d4a0bd0cd14f0d7a1cea19959b3291b4/templates/nro/.circleci/config.yml.tmpl

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,28 +1,122 @@
 ---
-version: 2
+version: 2.1
+
+parameters:
+  rollback:
+    type: boolean
+    default: false
+
+docker_auth: &docker_auth
+  username: $DOCKERHUB_USERNAME
+  password: $DOCKERHUB_PASSWORD
 
 defaults: &defaults
   docker:
     - image: greenpeaceinternational/p4-builder:latest
+      auth:
+        <<: *docker_auth
 
+orbs:
+  slack: circleci/slack@3.4.2
 job_environments:
-  common_environment: &common_environment
-    APP_HOSTPATH: gutenberg
-    CONTAINER_PREFIX: planet4-gutenberg
-    WP_DB_NAME_PREFIX: planet4-gutenber_wordpress
-  develop_environment: &develop_environment
-    APP_ENVIRONMENT: development
-    APP_HOSTNAME: www-dev.greenpeace.org
-    CLOUDSQL_INSTANCE: p4-develop-k8s
-    GOOGLE_PROJECT_ID: planet-4-151612
-    GCLOUD_CLUSTER: p4-development
-    HELM_NAMESPACE: develop
-    HELM_RELEASE: planet4-gutenberg
-    NEWRELIC_APPNAME: P4 gutenberg Development
-    WP_DB_NAME: planet4-gutenber_wordpress_develop
-    WP_STATELESS_BUCKET: planet4-gutenberg-stateless-develop
+    common_environment: &common_environment
+      APP_HOSTPATH: gutenberg
+      CONTAINER_PREFIX: planet4-gutenberg
+      WP_DB_NAME_PREFIX: planet4-gutenber_wordpress
+    develop_environment: &develop_environment
+      APP_ENVIRONMENT: development
+      APP_HOSTNAME: www-dev.greenpeace.org
+      CLOUDSQL_INSTANCE: p4-develop-k8s
+      GOOGLE_PROJECT_ID: planet-4-151612
+      GCLOUD_CLUSTER: p4-development
+      HELM_NAMESPACE: develop
+      HELM_RELEASE: planet4-gutenberg
+      NEWRELIC_APPNAME: P4 gutenberg Development
+      WP_DB_NAME: planet4-gutenber_wordpress_develop
+      WP_STATELESS_BUCKET: planet4-gutenberg-stateless-develop
+
+commands:
+  approve_job:
+    description: "Approve an on-hold job."
+    parameters:
+      job_name:
+        type: string
+    steps:
+      - run:
+          name: Unhold job "<< parameters.job_name >>"
+          command: |
+            if [ -f /tmp/workspace/approve_workflow ]; then
+              WORKFLOW_ID=$(cat /tmp/workspace/approve_workflow)
+              url="https://circleci.com/api/v2/workflow/$WORKFLOW_ID/job"
+
+              # Get workflow details
+              workflow=$(curl -s -u "${CIRCLE_TOKEN}": -X GET --header "Content-Type: application/json" "$url")
+              echo $workflow
+              # Get approval job id
+              job_id=$(echo "$workflow" | jq -r '.items[] | select(.name=="<< parameters.job_name >>") | .approval_request_id ')
+              echo $job_id
+
+              if [[ -z $job_id ]]; then
+                echo "Approval ID not found"
+                exit 1
+              fi
+
+              echo "Approving << parameters.job_name >> for workflow $url"
+              echo "Job ID: ${job_id}"
+              curl \
+                --header "Content-Type: application/json" \
+                -u "${CIRCLE_TOKEN}:" \
+                -X POST \
+                "https://circleci.com/api/v2/workflow/${CIRCLE_WORKFLOW_ID}/approve/${job_id}"
+            fi
 
 job_definitions:
+  visualtests_reference_steps: &visualtests_reference_steps
+    docker:
+      - image: greenpeaceinternational/planet4-backstop:latest
+        auth:
+          <<: *docker_auth
+    working_directory: /src
+    steps:
+      - run: ./checkout.sh
+      - run: ./mergescenarios.sh
+      - run: mkdir /app/ -p
+      - run: ./makehistory.sh
+      - store_artifacts:
+          path: /app/backstop_data
+      - persist_to_workspace:
+          root: /app
+          paths:
+            - backstop_data
+
+  visualtests_compare_steps: &visualtests_compare_steps
+    docker:
+      - image: greenpeaceinternational/planet4-backstop:latest
+        auth:
+          <<: *docker_auth
+    working_directory: /src
+    parameters:
+      notify:
+        type: boolean
+        default: false
+    steps:
+      - run: ./checkout.sh
+      - run: ./mergescenarios.sh
+      - run: mkdir /app/ -p
+      - attach_workspace:
+          at: /app
+      - run: ./makecomparison.sh
+      - store_artifacts:
+          path: /app/backstop_data
+      - when:
+          condition: << parameters.notify >>
+          steps:
+            # Notify p4-activity-ci
+            - slack/status:
+                fail_only: true
+                channel: C015MQGG3KQ
+                webhook: ${SLACK_NRO_WEBHOOK}
+
   build_steps: &build_steps
     working_directory: ~/
     steps:
@@ -37,14 +131,17 @@ job_definitions:
       - run: |
           if [[ -d source/cache ]]; then ls -al source/cache; fi
       - run: activate-gcloud-account.sh
-      - run: mkdir -p /tmp/workspace/var
-      - run: mkdir -p /tmp/workspace/src
+      - run: mkdir -p /tmp/workspace/var /tmp/workspace/src
       - run: echo "${CIRCLE_BUILD_NUM}" > /tmp/workspace/var/circle-build-num
-      - run: make
-      - run:
-          name: Notify failure
-          when: on_fail
-          command: TYPE="Build" notify-job-failure.sh
+      - run: make test
+      - run: make rewrite
+      - run: make checkout
+      - run: make rewrite-app-repos
+      - run: make copy
+      - run: make bake
+      - run: make persist
+      - run: make build
+      - run: make push
       - save_cache:
           key: composer-v5-{{ .Branch }}-{{ .Revision }}-{{ .BuildNum }}
           paths:
@@ -55,21 +152,103 @@ job_definitions:
             - var
             - src
 
+  test_steps: &test_steps
+    working_directory: ~/project
+    docker:
+      - image: greenpeaceinternational/p4-codeception:latest
+        auth:
+          <<: *docker_auth
+      - name: selenium
+        image: selenium/standalone-chrome-debug:3.141.59-oxygen
+        auth:
+          <<: *docker_auth
+    steps:
+      - checkout
+      - run: if [ ! -d "tests" ] || [ ! "$(ls -A tests)" ]; then circleci-agent step halt; fi
+      - run: dockerize -wait tcp://selenium:4444
+      - run: codeceptionify.sh .
+      - run: codecept run --xml=junit.xml --html
+      - run:
+          name: Copy test artifacts
+          when: always
+          command: |
+            mkdir -p /tmp/artifacts
+            cp -r codeception/_output/. /tmp/artifacts
+      - store_test_results:
+          path: /tmp/artifacts
+      - store_artifacts:
+          path: /tmp/artifacts
+
   deploy_steps: &deploy_steps
     working_directory: ~/
+    parameters:
+      notify:
+        type: boolean
+        default: false
+      is_prod:
+        type: boolean
+        default: false
     steps:
+      - checkout:
+          path: /home/circleci/checkout
       - attach_workspace:
           at: /tmp/workspace
       - run: activate-gcloud-account.sh
-      - run: BUILD_TAG=build-$(cat /tmp/workspace/var/circle-build-num) make -j2 deploy
+      - run: make prepare-helm
+      - run: make backup
+      - run: BUILD_TAG=build-$(cat /tmp/workspace/var/circle-build-num) make deploy-helm
+      - run: make post-deploy
+      - run:
+          name: Extract workflow from commit message
+          command: |
+            UNHOLD_WORKFLOW_LINE=$(git --git-dir=/home/circleci/checkout/.git log --format=%B -n 1 "$CIRCLE_SHA1" | { grep '^\/unhold ' || true; } )
+            echo "line $UNHOLD_WORKFLOW_LINE"
+            if [[ -n $UNHOLD_WORKFLOW_LINE ]]; then
+              WORKFLOW_ID=${UNHOLD_WORKFLOW_LINE#"/unhold "}
+              echo "$WORKFLOW_ID"
+              echo $WORKFLOW_ID > /tmp/workspace/approve_workflow
+            fi
+      - approve_job:
+          job_name: instance-ready
+      - when:
+          condition: << parameters.is_prod >>
+          steps:
+            - run: echo $CIRCLE_WORKFLOW_ID > /tmp/workspace/approve_workflow
+            - approve_job:
+                job_name: rollback-staging
+      - when:
+          condition: << parameters.notify >>
+          steps:
+            # Notify p4-activity-ci
+            - slack/status:
+                channel: C015MQGG3KQ
+                webhook: ${SLACK_NRO_WEBHOOK}
 
 jobs:
-  build-branch:
+  visualtests-reference-develop:
+    environment:
+      <<: *common_environment
+      <<: *develop_environment
+    <<: *visualtests_reference_steps
+
+  visualtests-compare-develop:
+    environment:
+      <<: *common_environment
+      <<: *develop_environment
+    <<: *visualtests_compare_steps
+
+  build-develop:
     <<: *defaults
     environment:
       <<: *common_environment
       <<: *develop_environment
     <<: *build_steps
+
+  test-develop:
+    environment:
+      <<: *common_environment
+      <<: *develop_environment
+    <<: *test_steps
 
   deploy-develop:
     <<: *defaults
@@ -77,22 +256,50 @@ jobs:
       <<: *common_environment
       <<: *develop_environment
     <<: *deploy_steps
-
+  data-sync:
+    <<: *defaults
+    environment:
+      <<: *common_environment
+      <<: *develop_environment
+    working_directory: /tmp/workspace/src
+    steps:
+      - checkout
+      - attach_workspace:
+          at: /tmp/workspace
+      - run:
+          name: Configure
+          command: |
+            activate-gcloud-account.sh
+      - run: sync_to_test_site.sh
 
 workflow_definitions:
-  develop_common: &develop_common
+  on_develop_commit: &on_develop_commit
     context: org-global
     filters:
       branches:
-        only: develop
+        only: main
 
 workflows:
-  version: 2
   develop:
     jobs:
-      - build-branch:
-          <<: *develop_common
+      - visualtests-reference-develop:
+          <<: *on_develop_commit
+      - build-develop:
+          <<: *on_develop_commit
       - deploy-develop:
-          <<: *develop_common
+          <<: *on_develop_commit
           requires:
-            - build-branch
+            - build-develop
+            - visualtests-reference-develop
+      - test-develop:
+          <<: *on_develop_commit
+          requires:
+            - deploy-develop
+      - visualtests-compare-develop:
+          <<: *on_develop_commit
+          requires:
+            - deploy-develop
+      - data-sync:
+          <<: *on_develop_commit
+          requires:
+            - deploy-develop
